In [4]:
import pandas as pd
import numpy as np

employee_data = pd.DataFrame({
    "Experience": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Salary": [
        30000, 35000, 40000, 45000, 50000,
        55000, 60000, 65000, 70000, 150000
    ],
    "Performance": [55, 60, 58, 65, 70, 72, 78, 80, 85, 90]
})

employee_data

   Experience  Salary  Performance
0           1   30000           55
1           2   35000           60
2           3   40000           58
3           4   45000           65
4           5   50000           70
5           6   55000           72
6           7   60000           78
7           8   65000           80
8           9   70000           85
9          10  150000           90

In [6]:
mean_salary = np.mean(employee_data["Salary"])
median_salary = np.median(employee_data["Salary"])
performance_series = pd.Series(employee_data["Performance"])
mode_performance = performance_series.mode() 
salary_range = np.max(employee_data["Salary"]) - np.min(employee_data["Salary"])
salary_variance = np.var(employee_data["Salary"])
salary_std = np.std(employee_data["Salary"])
Q1 = np.percentile(employee_data["Salary"], 25)
Q3 = np.percentile(employee_data["Salary"], 75)
IQR = Q3 - Q1
upper_outlier_boundary = Q3+1.5*IQR
lower_outlier_boundary = Q1-1.5*IQR
salary_outlier = employee_data["Salary"][
    (employee_data["Salary"]<lower_outlier_boundary) | 
    (employee_data["Salary"]>upper_outlier_boundary)
    ]

In [9]:
print("Mean Salary:", mean_salary)
print("Median Salary:", median_salary)
print("Mode Performance:", mode_performance.tolist())

print("Salary Range:", salary_range)
print("Salary Variance:", salary_variance)
print("Salary Standard Deviation:", salary_std)

print("Q1 (25th Percentile):", Q1)
print("Q3 (75th Percentile):", Q3)
print("IQR:", IQR)

print("Lower Outlier Boundary:", lower_outlier_boundary)
print("Upper Outlier Boundary:", upper_outlier_boundary)

print("Salary Outliers:" , salary_outlier)

Mean Salary: 60000.0
Median Salary: 52500.0
Mode Performance: [55, 58, 60, 65, 70, 72, 78, 80, 85, 90]
Salary Range: 120000
Salary Variance: 1050000000.0
Salary Standard Deviation: 32403.7034920393
Q1 (25th Percentile): 41250.0
Q3 (75th Percentile): 63750.0
IQR: 22500.0
Lower Outlier Boundary: 7500.0
Upper Outlier Boundary: 97500.0
Salary Outliers: 9    150000
Name: Salary, dtype: int64

In [10]:
employee_data["Experience"].corr(employee_data["Salary"])

np.float64(0.8058229640253802)

In [11]:
employee_data["Experience"].corr(employee_data["Performance"])

np.float64(0.9901069329905511)

In [12]:
employee_data["Salary"].corr(employee_data["Performance"])

np.float64(0.8228693171094775)

In [13]:
correlation_matrix = employee_data.corr()

correlation_matrix

             Experience    Salary  Performance
Experience     1.000000  0.805823     0.990107
Salary         0.805823  1.000000     0.822869
Performance    0.990107  0.822869     1.000000